### ISSUE TITLE
滚动写的过程中buf可用size 好像跟预期不符

### ISSUE THREAD

**Issue by llyp** [hungrybirder/limitedbuffer#1]
![image](https://user-images.githubusercontent.com/17312537/119595237-d149e580-be0f-11eb-8313-fde2e0a8e0fc.png)

bufsize 定义为8；
1. 先写入 5个，剩余3个
2. 读出 3 个， 剩余 6个
3. 写 6个失败，只能写入 5个

**Comment by hungrybirder** [comment]
这不是问题，因为要支持循环写， 当rpos和wpos不相等时，最多写到rpos-1，当rpos和wpos相等时，可以写capacity.

https://github.com/hungrybirder/limitedbuffer/blob/main/cyclebuffer.go#L177

**Comment by hungrybirder** [comment]
每次能写多少，可通过Status得知 `cb.Status().FreeWriteSpace()`
